#version: "3.9"

# Usage
# -----
#
# Make sure you created and configured your .env.local, and then run:
#     docker compose up
#

services:
  bot:
    build: .
    container_name: mjbot
    volumes:
    - "./docker/volumes/var:/bot/var"
